languageCode = "de"
languageName = "Deutsch"
displayName = "🇩🇪"
isoCode = "de"
weight = 1
rtl = false

title = "Jan Kremer"
# logo = "img/pharmacist-0.png"
description = "Willkommen auf meinem Blog 🧪"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2006-01-02"

[author]
name = "Jan Kremer"
image = "img/pharmacist-0.png"
# headline = "Mein Name ist Jan Kremer. Ich bin 25 Jahre alt und studiere Pharmazie an der Uni Regensburg. Nebenher lerne ich, wie man Webseiten erstellt und wie man Apps in Swift programmiert. Wenn ich nicht gerade lerne, mache ich gerne Sport, vor allem Laufen, Skifahren und Radfahren."
bio = "Ich bin 25 Jahre alt und studiere Pharmazie an der Uni Regensburg. Nebenher lerne ich, wie man Webseiten erstellt und wie man Apps in Swift programmiert."
links = [
  { email = "mailto:mail@jankremer.eu" },
  { key = "http://jankremer.eu/about/#pgp" },
  { github = "https://github.com/janurskremer" },
  { rss = "https://jankremer.eu/index.xml" },
  #   { link = "https://jankremer.eu/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { linkedin = "https://linkedin.com/in/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { twitter = "https://twitter.com/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
]
